### ISSUE TITLE
dev mode url

### ISSUE THREAD

**Issue by jteegarden** [zaidakram/expedia#15]
Kept getting a 403 response in dev mode.. I had to change the DEVELOPMENT_SERVER to api.ean.com from dev.api.ean.com in http_service.rb, once I did I started getting response 200 in development mode..

**Comment by zaidakram** [comment]
Are you behind a proxy or something? Because it working for me and everyone else. And you are only one reporting this kind of issue.

**Comment by veekram** [comment]
Had same issue. Changed DEVELOPMENT_SERVER to api.ean.com. And it worked like a charm!

**Comment by zaidakram** [comment]
Alright! Reverted back to api.ean.com. I also started facing the same problem. Though it was working fine a few days ago.
