### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by arkat19C** [zaidakram/expedia#16]
For me, even copying the exact code written on this repository's home page in to my program gives me an error. It says: "in `add_timeouts': undefined method `present?' for nil:NilClass (NoMethodError)". Any ideas why? Or what I'm doing wrong.

**Comment by zaidakram** [comment]
Could you paste the code you are using?

**Comment by zaidakram** [comment]
Alright, changes pushed on master. I'll be releasing a new version soon. In the meantime you can use master.
