### ISSUE TITLE
#<Expedia::APIError: Expedia::APIError>

### ISSUE THREAD

**Issue by veekram** [zaidakram/expedia#17]
After upgrading to version to 0.0.5, I am getting the above mentioned error. The status response is 400.
I am simply making request as:

list_api = Expedia.Api.new
response = list_api.get_payment_info( {:hotelID => 172396)

Am not I supposed to get the response.body?

**Comment by zaidakram** [comment]
In case of any error a Expedia::APIError object is returned.

Are you using API in sandbox mode, with cid of 55505?

**Comment by veekram** [comment]
Yes I do. Is not that supposed to work with sandbox mode?

**Comment by zaidakram** [comment]
It should work in every mode. Just wanted to know if you having issue in sandbox or live mode...

**Comment by veekram** [comment]
It was working fine with the prior version without any problems. I hope , there are some major changes on the expedia api and  they must have changed the request URL too.  I didnot find any docs related to changing to the URL though.

**Comment by zaidakram** [comment]
The gem first used api.ean.com. But then EAN introduced a separate dev api on dev.api.ean.com. But I think they discontinued it, or something. Some folks here were having issue with it but I wasn't. Now that you've reported it again, I was able to reproduce the issue. So reverting back to api.ean.com should work now.
